config:
    send_anonymous_usage_stats: False
    use_colors: True

integration_tests:
  outputs:
    duckdb:
      type: duckdb
      path: ":memory:"
      database: memory
      external_root: tmp/materialized # Materialize Models as CSV for Inspection

    postgres:
      type: postgres
      threads: 2
      host: localhost
      port: 5432
      user: ""
      pass: ""
      dbname: dbt_aql_integration_tests
      schema: main

    bigquery:
      type: bigquery
      method: service-account
      project: dbt-aql
      dataset: dbt_aql_integration_tests
      threads: 4 # Must be a value of 1 or greater
      keyfile: tbd # need to update for CI
      OPTIONAL_CONFIG: VALUE

  target: duckdb
