name: CI
on:
  workflow_call:
    inputs:
      target:
        type: string
        required: true
    
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Build dbt Integration Tests Project
        run: |
          pwd
          dbt build -x --target ${{ inputs.target }}
        env:
          GCP_KEYFILE_PATH: ./gcp_keyfile.json
          DBT_PROFILES_DIR: . # Use integration_tests/profiles.yml


