name: CI - Pull Request
on: 
  pull_request:
    branches: [ main ]

jobs:
  setup:
    uses: ./.github/workflows/setup.yml
    with:
      gcp_keyfile_path: ./integration_tests/gcp_keyfile.json
    secrets:
      gcp_keyfile: ${{ secrets.GCP_KEYFILE }}

  duckdb:
    needs: [ setup ]
    uses: ./.github/workflows/ci.yml
    with:
      target: bigquery

  bigquery:
    needs: [ setup ]
    uses: ./.github/workflows/ci.yml
    with:
      target: bigquery
