name: CI - Pull Request
on: 
  pull_request:
    branches: [ main ]

jobs:
  CI:
    uses: ./.github/workflows/ci.yml
    with:
      gcp_keyfile_path: ./integration_tests/gcp_keyfile.json
    secrets:
      gcp_keyfile: ${{ secrets.GCP_KEYFILE }}
