name: Setup
on:
  workflow_call:
    inputs:
      gcp_keyfile_path:
        type: string
        required: true
    secrets:
      gcp_keyfile:
        required: true
    
jobs:
  setup:
    runs-on: ubuntu-latest
    env:
      GCP_KEYFILE: ${{ secrets.GCP_KEYFILE }}

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python -
      - name: Install Python Dependencies
        run: pip install -r poetry.lock
      - name: Publish GCP Keyfile
        run: echo $GCP_KEYFILE > ${{ inputs.gcp_keyfile_path }}
      - name: Run dbt deps
        run: |
          cd ./integration_tests
          dbt deps
